    
variable = {
    'jpt_1': {
        'title' : "jet 1 p_{T} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 4000,
        'log' : True,
    },
    'jpt_2': {
        'title' : "jet 2 p_{T} (GeV)",
        'nbins' : 100,
        'min' : 0,
        'max' : 4000,
        'log' : True,
    },
    'jeta_1': {
        'title' : "jet 1 #eta",
        'nbins' : 100,
        'min' : 0,
        'max' : 5,
        'log' : False,
    },
    'jeta_2': {
        'title' : "jet 2 #eta",
        'nbins' : 100,
        'min' : 0,
        'max' : 5,
        'log' : False,
    },
    'jphi_1': {
        'title' : "jet 1 #phi",
        'nbins' : 100,
        'min' : -3.15,
        'max' : 3.15,
        'log' : False,
    },
    'jphi_2': {
        'title' : "jet 2 #phi",
        'nbins' : 100,
        'min' : -3.15,
        'max' : 3.15,
        'log' : False,
    },
    'jdeepCSV_1': {
        'title' : "jet 1 deepCSV",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'log' : False,
    },
    'jdeepCSV_2': {
        'title' : "jet 2 deepCSV",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'log' : False,
    },
    'jdeepFlavour_1': {
        'title' : "jet 1 deepFlavour",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'log' : False,
    },
    'jdeepFlavour_2': {
        'title' : "jet 2 deepFlavour",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'log' : False,
    },
    'jj_mass': {
        'title' : "m_{jj} (GeV)",
        'nbins' : 90,
        'min' : 0,
        'max' : 9000,
        'log' : True,
    },
    'jj_deltaEta': {
        'title' : "#Delta #eta_{jj}",
        'nbins' : 80,
        'min' : 0,
        'max' : 5,
        'log' : False,
    },
    'jj_deltaPhi': {
        'title' : "#Delta #phi{jj}",
        'nbins' : 80,
        'min' : 0,
        'max' : 5,
        'log' : False,
    },
    'MET_over_SumEt': {
        'title' : "#slash{E_{T}} / #sum{E_{T}}",
        'nbins' : 50,
        'min' : 0,
        'max' : 1,
        'log' : False,
    },
    'njets': {
        'title' : "number of jets",
        'nbins' : 9,
        'min' : -0.5,
        'max' : 8.5,
        'log' : True,
    },
    'jj_mass_widejet': {
        'title' : "m_{jj} (GeV)",
        'nbins' : 90,
        'min' : 1400,
        'max' : 9000,
        'log' : True,
    },
    'jnmuons_1':{
        'title' : "n_{#mu, jet1}",
        'nbins' : 30,
        'min' : 0,
        'max' : 30,
        'log' : False,
    },  
     'jnmuons_2':{
        'title' : "n_{#mu, jet2}",
        'nbins' : 30,
        'min' : 0,
        'max' : 30,
        'log' : False,
    },  
    'fatjetmass_1':{
        'title' : "m_{fatjet}",
        'nbins' : 100,
        'min'   : 0,
        'max'   : 2000,
        'log'   : True,
    },
}

